"""All of our data in one file + a generated catalog.

  uv run python scripts/data/build_all.py

- data/all.jsonl.gz: every ORIGINAL question once (one JSON line per question, the usual schema) with one extra field,
  `dataset`. Derived views (option-list transforms, subsets, teacher labels, fixtures) are left out and listed in the
  catalog instead. Rows keep their own `split`: filter on it, and never train on `test` rows.
  Load: selfjev.data.load(["data/all.jsonl.gz"]) or gzip + json. Rebuildable, so it is not tracked in git.
- `jev` field: Jev's prediction for the row (P(yes) or per-candidate probabilities, answer, confidence, correct, Jev
  version) from data/jev/predictions.jsonl (scripts/data/jev_predictions.py), only when the text and question are unchanged.
- data/README.md: the catalog (generated from selfjev.data.catalog: edit DATASETS / DERIVED there, not the file).
"""

import gzip
import json
import sys
from collections import Counter
from pathlib import Path

from selfjev.data import load, sha256_file
from selfjev.data.catalog import DERIVED, datasets, request_sha

ROOT = Path(__file__).resolve().parents[2]


def main():
    out, stats, total = ROOT / "data/all.jsonl.gz", [], 0
    seen = set()
    jp = ROOT / "data/jev/predictions.jsonl"
    jev = {}
    if jp.exists():
        with open(jp) as f:
            jev = {r["id"]: r for r in map(json.loads, f)}
    with gzip.open(out, "wt", encoding="utf-8") as f:
        for name, path, *_ in datasets(ROOT):
            rows = load([ROOT / path])
            dup = seen & {r["id"] for r in rows}
            if dup:
                sys.exit(f"{path}: {len(dup)} ids already in another dataset, e.g. {sorted(dup)[:3]}")
            seen |= {r["id"] for r in rows}
            for r in rows:
                p = jev.get(r["id"])
                if p and p["request"] == request_sha(r):
                    r["jev"] = {k: v for k, v in p.items() if k not in ("id", "dataset", "request")}
                f.write(json.dumps({"dataset": name, **r}, ensure_ascii=False) + "\n")
            total += len(rows)
            stats.append((name, rows, sha256_file(ROOT / path)))
            print(f"{name}: {len(rows)} questions", flush=True)

    def jev_cell(rows):
        j = [r["jev"]["correct"] for r in rows if "jev" in r]
        return f"{len(j):,} / {100 * sum(j) / len(j):.1f}%" if j else "—"

    def fmt(c):
        return ", ".join(f"{k} {v:,}" for k, v in c.most_common())

    lines = [
        "# Our data",
        "",
        "Generated by `uv run python scripts/data/build_all.py` (edit the lists in `src/selfjev/data/catalog.py`, not this file). "
        "Every row is one question about one text: `id`, `source_id`, `family`, `split`, `provenance`, `state`, "
        "`question` (`type`, `instruction`, `candidates`), `target`, `hard_cases`; schema and labeling policy in "
        "[docs/data.md](../docs/data.md).",
        "",
        f"**All original questions in one file: `data/all.jsonl.gz`**: {total:,} questions from {len(stats)} datasets, "
        "each row tagged with `dataset`. Built locally by the command above (not tracked in git). Load it with "
        '`selfjev.data.load(["data/all.jsonl.gz"])`, then filter on `dataset` and `split`.',
        "",
        "**Jev's prediction** is stored on each row it exists for, as `jev`: `p_yes` (binary) or `probs` per candidate, `answer`, "
        "`confidence`, `correct` (vs `target`), `model` (Jev version). Source: `data/jev/predictions.jsonl` "
        "(`scripts/data/jev_predictions.py`). Jev's outputs never replace `target`.",
        "",
        "**Rules:** never train on, or tune anything on, `test` rows. `eval2`, `eval_llm` and `compact_challenge_v1` are frozen test sets. "
        "The `test` rows of `hf` and `eval` form the development benchmark (3,471 questions), reused for many decisions.",
        "",
        "## Always use this file",
        "",
        "Every training mix, evaluation and analysis starts from `data/all.jsonl.gz` (run the build command if it is missing):",
        "",
        "```python",
        "from selfjev.data import load",
        'rows = load(["data/all.jsonl.gz"])',
        'TEST = {"eval", "eval2", "eval_llm", "compact_challenge_v1"}          # selfjev.data.catalog.TEST_DATASETS',
        'train = [r for r in rows if r["dataset"] not in TEST and r["split"] == "train"]',
        'val   = [r for r in rows if r["dataset"] not in TEST and r["split"] == "validation"]',
        'eval2 = [r for r in rows if r["dataset"] == "eval2"]                    # frozen: report only',
        'teacher = [r["jev"] for r in train if "jev" in r]                     # Jev\'s probabilities, never the label',
        "```",
        "",
        "Recipes on top (not baked into the file): the best models cap `none`-correct round-2 questions at 10% "
        "(`scripts/data/rebalance_nota.py`), list every option in the question (`scripts/data/options_in_question.py`, also at serving "
        "time) and cap public families at 1,600 questions ([docs/data.md](../docs/data.md#the-training-mixes)).",
        "",
        "## Grow it: add a batch, never a new stand-alone dataset",
        "",
        "1. **Write** into a named batch (any brief/mode flag works; one run per writer model; each paid run needs the user's OK "
        "with a price): `zsh -ic 'uv run python scripts/data/gen_hardcases.py --batch <name> --model <writer> --budget <usd> "
        "[--usecases train | --round3]'`. "
        "Balance and variety come from the generator (tiers, text lengths 8 to 8K tokens, traps, instruction styles). "
        "Default writers: GPT-6 Luna and Gemini 3.8 Flash. Not Grok 4.7 (mandatory hidden reasoning, ~20K output tokens per call, "
        "2-3x the cost per kept question), not DeepSeek V4 Flash (74% judge agreement), never the test sets' writers (Opus, "
        "Kimi, GLM). No third writer for now (user, 2026-09-26). Gemini at half price: "
        "`zsh -ic 'uv run python scripts/data/gen_gemini_batch.py submit --batch <name> --calls <n> [same mode flags]'`, then "
        "`... collect --batch <name> --wait` (Google Batch API, up to 24 h; plan balanced up front).",
        "2. **Judge** blind: `bash scripts/data/grow_batch.sh <name> judge` (GPT-6 Astra batch, ≈ $4 per 1K questions).",
        "3. **Build and screen**: `bash scripts/data/grow_batch.sh <name> build`: strict build (a text is dropped when any of its "
        "questions is flagged), overlap guard against every test set, OpenAI moderation screen (free). Read the flagged texts "
        "and delete unsafe ones from `data/batches/<name>/raw/` (rules: [docs/llm_eval_data.md](../docs/llm_eval_data.md)), then "
        "rerun `build`. Write one line describing the batch in `data/batches/<name>/README.md`.",
        "4. **Finish**: `bash scripts/data/grow_batch.sh <name> finish`: Jev's predictions for the new questions (≈ $0.03 per 1K) "
        "and a rebuild of `data/all.jsonl.gz` and this catalog. The batch is now part of the file under `dataset = <name>`.",
        "",
        "New frozen test sets are the exception: built on purpose with other writers and two judges (like `eval_llm`), then "
        "added to `DATASETS` and `TEST_DATASETS` in `src/selfjev/data/catalog.py`.",
        "",
        "## Datasets in all.jsonl.gz",
        "",
        "| dataset | file | what | used as | questions | texts | splits | types | Jev: have / accuracy | write-up |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for (name, path, what, role, doc), (_, rows, _sha) in zip(datasets(ROOT), stats):
        lines.append(
            f"| **{name}** | `{path}` | {what} | {role} | {len(rows):,} | {len({r['source_id'] for r in rows}):,} | "
            f"{fmt(Counter(r['split'] for r in rows))} | {fmt(Counter(r['question']['type'] for r in rows))} | "
            f"{jev_cell(rows)} | [link](../{doc}) |"
        )
    by_split = Counter(r["split"] for _, rows, _ in stats for r in rows)
    lines += [
        f"| **total** | `data/all.jsonl.gz` | | | **{total:,}** | | {fmt(by_split)} | | "
        f"{jev_cell([r for _, rows, _ in stats for r in rows])} | |",
        "",
        "## Left out on purpose (derived views, subsets, non-ground-truth labels, fixtures)",
        "",
        "| path | what |",
        "|---|---|",
    ]
    lines += [f"| `{p}` | {w} |" for p, w in DERIVED]
    lines += ["", "## sha256 of the source files", ""] + [
        f"- `{path}`: `{sha[:16]}…`" for (_, path, *_), (_, _, sha) in zip(datasets(ROOT), stats)
    ]
    (ROOT / "data/README.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({total} questions, {out.stat().st_size / 1e6:.0f} MB) and data/README.md")


if __name__ == "__main__":
    main()
