"""What existing eval2 predictions say about Jev and about combining our models, at $0 (no model runs).

Reads reports/*/eval2/report.json, reports/external/eval2/typesafe_jev-latest/report.json and
reports/teacher/qwen38_27b_eval2.jsonl, and writes reports/eval2/ensembles.md:
- Jev's probability granularity and how hedged its errors are, vs ours;
- pairwise oracles ("either right"), fixed 50/50 probability averages (nothing fitted);
- confidence cascades: the primary model answers when its margin >= tau, otherwise a fallback answers. The whole
  curve is reported; tau must be chosen on validation, never on eval2.

usage: python3 scripts/ensemble_eval2.py
"""
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNS = {"qwen35_4b_tree": "reports/qwen35_4b_tree/eval2/report.json",
        "tree_4b_combo": "reports/tree_4b_combo/eval2/report.json",
        "qwen35_4b_r2x64": "reports/qwen35_4b_r2x64/eval2/report.json",
        "tree_4b_instruct_r3": "reports/tree_4b_instruct_r3/eval2/report.json",
        "eikos_4b": "reports/eikos_4b/eval2/report.json",
        "jev": "reports/external/eval2/typesafe_jev-latest/report.json"}
TAUS = (0.1, 0.2, 0.3, 0.4, 0.45)


def load():
    preds = {k: {x["id"]: x for x in json.loads((ROOT / v).read_text())["predictions"]} for k, v in RUNS.items()}
    preds["teacher_27b"] = {}
    for line in (ROOT / "reports/teacher/qwen38_27b_eval2.jsonl").read_text().splitlines():
        x = json.loads(line)
        x["probabilities"] = x.pop("p")
        preds["teacher_27b"][x["id"]] = x
    ids = sorted(set.intersection(*(set(v) for v in preds.values())))
    ref = preds["tree_4b_combo"]  # candidate order reference; every file scores the same expanded rows
    for k in preds:  # the teacher file has no candidate ids of its own; every file scores the same expanded rows
        assert all(preds[k][i].get("candidate_ids", ref[i]["candidate_ids"]) == ref[i]["candidate_ids"] for i in ids), k
    return preds, ids, ref


def decide(t, p, cids):
    if t == "binary":
        return p[0] >= 0.5
    if t == "multiclass":
        return cids[max(range(len(p)), key=p.__getitem__)]
    return sorted(c for c, v in zip(cids, p) if v >= 0.5)


def target(rec):
    return sorted(rec["target"]) if isinstance(rec["target"], list) else rec["target"]


def margin(t, p):
    if t == "binary":
        return abs(p[0] - 0.5)
    if t == "multiclass":
        s = sorted(p, reverse=True)
        return s[0] - (s[1] if len(s) > 1 else 0.0)
    return min(abs(v - 0.5) for v in p)


def main():
    preds, ids, ref = load()
    n = len(ids)
    ok = {k: {i: bool(preds[k][i]["correct"]) for i in ids} for k in preds}
    best = max((k for k in preds if k != "jev"), key=lambda k: sum(ok[k].values()))
    acc = lambda o: 100 * sum(o[i] for i in ids) / n
    types = {t: [i for i in ids if ref[i]["type"] == t] for t in ("binary", "multiclass", "multilabel")}
    by_type = lambda o: " / ".join(f"{100 * sum(o[i] for i in q) / len(q):.1f}" for q in types.values())

    def ens(ks):
        out = {}
        for i in ids:
            ps = [preds[k][i]["probabilities"] for k in ks]
            avg = [sum(p[j] for p in ps) / len(ps) for j in range(len(ps[0]))]
            out[i] = decide(ref[i]["type"], avg, ref[i]["candidate_ids"]) == target(ref[i])
        return out

    def cascade(primary, fallback_ok):
        rows = []
        for tau in TAUS:
            defer = [i for i in ids if margin(ref[i]["type"], preds[primary][i]["probabilities"]) < tau]
            o = {i: (fallback_ok[i] if i in set(defer) else ok[primary][i]) for i in ids}
            rows.append(f"| {tau} | {100 * len(defer) / n:.1f} | {acc(o):.1f} |")
        return rows

    L = ["# eval2: probabilities, ensembles and cascades (generated by `scripts/ensemble_eval2.py`, $0)", "",
         f"{n} questions. Nothing here is fitted: the averages are fixed 50/50, and the cascade tables show the whole "
         "threshold curve (choose a threshold on validation, never on eval2).", "",
         "## How confident are the models", "",
         "| model | eval2 | probabilities in (0.05, 0.95) | errors | errors with margin < 0.2 | errors with margin ≥ 0.4 |",
         "|---|---|---|---|---|---|"]
    for k in ("jev", "qwen35_4b_tree", "tree_4b_combo", "qwen35_4b_r2x64", "eikos_4b", "teacher_27b"):
        allp = [v for i in ids for v in preds[k][i]["probabilities"]]
        graded = 100 * sum(0.05 < v < 0.95 for v in allp) / len(allp)
        wrong = [i for i in ids if not ok[k][i]]
        m = [margin(ref[i]["type"], preds[k][i]["probabilities"]) for i in wrong]
        L.append(f"| {k} | {acc(ok[k]):.1f} | {graded:.1f}% | {len(wrong)} | {sum(v < 0.2 for v in m)} | {sum(v >= 0.4 for v in m)} |")
    jv = Counter(round(v, 4) for i in ids for v in preds["jev"][i]["probabilities"])
    L += ["", f"- Jev returns {len(jv)} distinct probability values, {sum(c for v, c in jv.items() if abs(v * 100 - round(v * 100)) < 1e-6)} "
          f"of {sum(jv.values())} are multiples of 0.01 (the API rounds to two decimals); most common: "
          + ", ".join(f"{v:g} ({c})" for v, c in jv.most_common(8)) + ".",
          "- Margin = |p − 0.5| (binary), top-1 − top-2 (multiclass), the least certain label's |p − 0.5| (multilabel).", "",
          "## Pairs and trios: oracle vs fixed 50/50 probability average", "",
          "| models | either right | average | average by type (binary / multiclass / multilabel) |", "|---|---|---|---|"]
    for ks in (("qwen35_4b_tree", "tree_4b_combo"), ("qwen35_4b_tree", "teacher_27b"), ("qwen35_4b_tree", "eikos_4b"),
               ("qwen35_4b_tree", "tree_4b_combo", "teacher_27b"), ("qwen35_4b_tree", "tree_4b_combo", "eikos_4b"),
               ("tree_4b_combo", "teacher_27b"), ("tree_4b_combo", "eikos_4b"), ("tree_4b_combo", "qwen35_4b_r2x64"),
               ("tree_4b_combo", "qwen35_4b_r2x64", "eikos_4b", "teacher_27b"), ("qwen35_4b_tree", "jev")):
        oracle = 100 * sum(any(ok[k][i] for k in ks) for i in ids) / n
        e = ens(ks)
        L.append(f"| {' + '.join(ks)} | {oracle:.1f} | **{acc(e):.1f}** | {by_type(e)} |")
    L += ["", f"## Cascades: `{best}` (the best single model) answers unless its margin is below tau", "",
          "The fallback answers the deferred questions. `→ Jev` is only an upper bound for a fallback stronger than the 27B.", ""]
    for name, fb in (("→ 50/50 average with the 27B teacher", ens((best, "teacher_27b"))),
                     ("→ 50/50 average with tree_4b_combo", ens((best, "tree_4b_combo"))),
                     ("→ 50/50 average with tree_4b_combo and the 27B teacher", ens((best, "tree_4b_combo", "teacher_27b"))),
                     ("→ the 27B teacher alone", ok["teacher_27b"]), ("→ tree_4b_combo alone", ok["tree_4b_combo"]), ("→ Jev", ok["jev"])):
        L += [f"### {name}", "", "| tau | deferred % | eval2 |", "|---|---|---|"] + cascade(best, fb) + [""]
    lost = [i for i in ids if ok["jev"][i] and not ok[best][i]]
    lm = [margin(ref[i]["type"], preds[best][i]["probabilities"]) for i in lost]
    L += [f"## Where `{best}` loses to Jev", "",
          f"- {len(lost)} questions Jev gets right and we get wrong: " + ", ".join(f"{t} {c}" for t, c in Counter(ref[i]['type'] for i in lost).most_common()) + ".",
          f"- On {sum(v < 0.2 for v in lm)} of them our margin is below 0.2 and on {sum(v < 0.4 for v in lm)} below 0.4: we are unsure on most of what we lose.", ""]
    out = ROOT / "reports/eval2/ensembles.md"
    out.write_text("\n".join(L))
    print("\n".join(L))


if __name__ == "__main__":
    main()
