"""eval2 scoreboard (frozen target-task test set, data/eval2.jsonl): every reports/**/eval2/report.json and
reports/external/eval2/*/report.json -> reports/eval2/summary.md, sliced by type, tier, author, text length and trap,
with paired exact McNemar tests vs round 1 (tree_4b) and vs Jev. Stdlib only.

usage: python3 scripts/eval2_summary.py      (re-run after scoring any model on eval2; never train or tune on eval2)
"""
import json
import math
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REF, JEV = "tree_4b", "jev"
LENGTHS = [(64, "≤64"), (256, "65–256"), (1024, "257–1K"), (4096, "1K–4K"), (10 ** 9, ">4K")]


def mcnemar(a, b):
    oa, ob = sum(a[i] and not b[i] for i in a), sum(b[i] and not a[i] for i in a)
    n, k = oa + ob, min(oa, ob)
    return oa, ob, (min(1.0, 2 * sum(math.comb(n, j) for j in range(k + 1)) / 2 ** n) if n else 1.0)


def main():
    author = {s["source_id"]: s["provenance"].split("/", 2)[-1].split(" (")[0]
              for s in map(json.loads, (ROOT / "data/eval2.jsonl").read_text().splitlines())}
    runs = {str(p.parent.parent.relative_to(ROOT / "reports")): p for p in sorted(ROOT.glob("reports/**/eval2/report.json"))
            if "external" not in p.parts}
    runs |= {"jev" if "jev" in p.parent.name else p.parent.name: p for p in sorted(ROOT.glob("reports/external/eval2/*/report.json"))
             if not p.parent.name.startswith("ours-")}
    preds = {k: {x["id"]: x for x in json.loads(p.read_text())["predictions"]} for k, p in runs.items()}
    ids = set.intersection(*(set(v) for v in preds.values()))
    assert all(len(v) == len(ids) for v in preds.values()), "runs scored different questions"
    order = sorted(preds, key=lambda k: -sum(bool(preds[k][i]["correct"]) for i in ids))

    def slice_rows(title, key, sort=None):
        groups = defaultdict(list)
        for i in ids:
            for g in key(preds[order[0]][i]):
                groups[g].append(i)
        out = [f"### {title}", "", "| slice | n | " + " | ".join(order) + " |", "|---|---|" + "---|" * len(order)]
        for g in sorted(groups, key=sort or (lambda g: (-len(groups[g]), g) if title == "trap" else g)):
            q = groups[g]
            out.append(f"| {g} | {len(q)} | " + " | ".join(f"{100 * sum(bool(preds[k][i]['correct']) for i in q) / len(q):.1f}"
                                                          for k in order) + " |")
        return out + [""]

    bucket = lambda x: [next(lab for hi, lab in LENGTHS if int(x["state_tokens"]) <= hi)]
    hc = lambda x: x["hard_cases"] if isinstance(x["hard_cases"], list) else json.loads(x["hard_cases"].replace("'", '"'))
    lines = ["# eval2 results (frozen target-task test set)", "",
             f"Generated by `python3 scripts/eval2_summary.py`; do not hand-edit. {len(ids)} questions, `data/eval2.jsonl` "
             "(see `data/eval2/REVIEW.md`). Never train, select prompts or fit calibration on it. GPT-6 Astra is one of the two "
             "judges that decided which questions were kept, so it is not a fair competitor here and isn't scored.", ""]
    lines += slice_rows("overall", lambda x: ["all"]) + slice_rows("type", lambda x: [x["type"]])
    lines += slice_rows("tier", lambda x: [x["family"]]) + slice_rows("author", lambda x: [author[x["source_id"]]])
    lines += slice_rows("text length (tokens)", bucket, sort=[lab for _, lab in LENGTHS].index) + slice_rows("trap", hc)
    lines += ["### paired exact McNemar (questions only the row / only the other gets right)", "",
              "| run | vs tree_4b | vs Jev |", "|---|---|---|"]
    ok = {k: {i: bool(preds[k][i]["correct"]) for i in ids} for k in order}
    for k in order:
        cells = [("—" if k == o or o not in ok else "{} / {} (p = {:.2g})".format(*mcnemar(ok[k], ok[o]))) for o in (REF, JEV)]
        lines.append(f"| {k} | " + " | ".join(cells) + " |")
    out = ROOT / "reports/eval2/summary.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
